export const PLAY_SONG = 'PLAY_SONG';
export const ADD_SONG_TO_QUEUE = 'ADD_SONG_TO_QUEUE';
export const SAVE_SONG_TO_LIBRARY = 'SAVE_SONG_TO_LIBRARY';
export const FOLLOW_USER = 'FOLLOW_USER';
export const DISPLAY_USERS_SONGS = 'DISPLAY_USERS_SONGS';
export const DISPLAY_USERS_ALBUMS = 'DISPLAY_USERS_ALBUMS';
export const FETCH_ERROR = 'FETCH_ERROR';
